#!/usr/bin/env python

import os
import subprocess

for python_version in ('2.7', '3.5', '3.6'):
    subprocess.check_call([
      'docker', 'build',
      '-t', 'base16-builder-ansible-test-{}'.format(python_version),
      '--build-arg', 'python_version={}'.format(python_version),
      os.path.abspath(os.path.dirname(__file__)),
    ])
    subprocess.check_call([
      'docker', 'run', 'base16-builder-ansible-test-{}'.format(python_version),
    ])
